version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: lms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lms_db
      MYSQL_USER: lms_user
      MYSQL_PASSWORD: lmspassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_lms_data:/var/lib/mysql

volumes:
  mysql_lms_data: